/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Tue Feb  5 17:06:07 2019. */

#ifndef PB_BLUETERA_MESSAGES_PB_H_INCLUDED
#define PB_BLUETERA_MESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct {
    char value[8];
/* @@protoc_insertion_point(struct:bluetera_echo_payload_t) */
} bluetera_echo_payload_t;

typedef struct {
    float x;
    float y;
    float z;
/* @@protoc_insertion_point(struct:bluetera_imu_acceleration_payload_t) */
} bluetera_imu_acceleration_payload_t;

typedef struct {
    float w;
    float x;
    float y;
    float z;
/* @@protoc_insertion_point(struct:bluetera_imu_quaternion_payload_t) */
} bluetera_imu_quaternion_payload_t;

typedef struct {
    uint32_t timestamp;
    pb_size_t which_payload;
    union {
        bluetera_imu_acceleration_payload_t acceleration;
        bluetera_imu_quaternion_payload_t quaternion;
    } payload;
/* @@protoc_insertion_point(struct:bluetera_bluetera_downlink_message_t) */
} bluetera_bluetera_downlink_message_t;

typedef struct {
    pb_size_t which_payload;
    union {
        bluetera_echo_payload_t echo;
    } payload;
/* @@protoc_insertion_point(struct:bluetera_bluetera_uplink_message_t) */
} bluetera_bluetera_uplink_message_t;

/* Default values for struct fields */

/* Initializer values for message structs */
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_INIT_DEFAULT {0, 0, 0}
#define BLUETERA_IMU_QUATERNION_PAYLOAD_INIT_DEFAULT {0, 0, 0, 0}
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_INIT_DEFAULT {0, 0, {BLUETERA_IMU_ACCELERATION_PAYLOAD_INIT_DEFAULT}}
#define BLUETERA_ECHO_PAYLOAD_INIT_DEFAULT       {""}
#define BLUETERA_BLUETERA_UPLINK_MESSAGE_INIT_DEFAULT {0, {BLUETERA_ECHO_PAYLOAD_INIT_DEFAULT}}
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_INIT_ZERO {0, 0, 0}
#define BLUETERA_IMU_QUATERNION_PAYLOAD_INIT_ZERO {0, 0, 0, 0}
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_INIT_ZERO {0, 0, {BLUETERA_IMU_ACCELERATION_PAYLOAD_INIT_ZERO}}
#define BLUETERA_ECHO_PAYLOAD_INIT_ZERO          {""}
#define BLUETERA_BLUETERA_UPLINK_MESSAGE_INIT_ZERO {0, {BLUETERA_ECHO_PAYLOAD_INIT_ZERO}}

/* Field tags (for use in manual encoding/decoding) */
#define BLUETERA_ECHO_PAYLOAD_VALUE_TAG          1
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_X_TAG  1
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_Y_TAG  2
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_Z_TAG  3
#define BLUETERA_IMU_QUATERNION_PAYLOAD_W_TAG    1
#define BLUETERA_IMU_QUATERNION_PAYLOAD_X_TAG    2
#define BLUETERA_IMU_QUATERNION_PAYLOAD_Y_TAG    3
#define BLUETERA_IMU_QUATERNION_PAYLOAD_Z_TAG    4
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_ACCELERATION_TAG 2
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_QUATERNION_TAG 3
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_TIMESTAMP_TAG 1
#define BLUETERA_BLUETERA_UPLINK_MESSAGE_ECHO_TAG 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t bluetera_imu_acceleration_payload_fields[4];
extern const pb_field_t bluetera_imu_quaternion_payload_fields[5];
extern const pb_field_t bluetera_bluetera_downlink_message_fields[4];
extern const pb_field_t bluetera_echo_payload_fields[2];
extern const pb_field_t bluetera_bluetera_uplink_message_fields[2];

/* Maximum encoded size of messages (where known) */
#define BLUETERA_IMU_ACCELERATION_PAYLOAD_SIZE   15
#define BLUETERA_IMU_QUATERNION_PAYLOAD_SIZE     20
#define BLUETERA_BLUETERA_DOWNLINK_MESSAGE_SIZE  28
#define BLUETERA_ECHO_PAYLOAD_SIZE               10
#define BLUETERA_BLUETERA_UPLINK_MESSAGE_SIZE    12

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLUETERA_MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
