#!/bin/sh
# modifies the version string in version.h to the first 8 chars of HEAD hash
# place this script under .git/hooks
cmt=$(git rev-list --max-count=1 HEAD | cut -c1-8)
file=./application/commit_hash.h

printf "/*** Autogenerated by git hooks. Do not add to source control. ***/\n\n" > $file
printf "#ifndef COMMIT_HASH_H_\n#define COMMIT_HASH_H_\n\n" >> $file
printf "#define SCM_COMMIT_HASH \"$cmt\"\n\n" >> $file
printf "#endif" >> $file
