# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluetera_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bluetera_messages.proto',
  package='bluetera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x62luetera_messages.proto\x12\x08\x62luetera\"\x1c\n\x0b\x45\x63hoPayload\x12\r\n\x05value\x18\x01 \x01(\r\"D\n\x05\x45rror\x12-\n\x06module\x18\x01 \x01(\x0e\x32\x1d.bluetera.BlueteraModulesType\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\"L\n\x16ImuAccelerationPayload\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"U\n\x14ImuQuaternionPayload\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\t\n\x01w\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\"\xd5\x01\n\x0f\x44ownlinkMessage\x12\x38\n\x0c\x61\x63\x63\x65leration\x18\x01 \x01(\x0b\x32 .bluetera.ImuAccelerationPayloadH\x00\x12\x34\n\nquaternion\x18\x02 \x01(\x0b\x32\x1e.bluetera.ImuQuaternionPayloadH\x00\x12 \n\x05\x65rror\x18\x10 \x01(\x0b\x32\x0f.bluetera.ErrorH\x00\x12%\n\x04\x65\x63ho\x18\x11 \x01(\x0b\x32\x15.bluetera.EchoPayloadH\x00\x42\t\n\x07payload\"y\n\x08ImuStart\x12\x12\n\ndata_types\x18\x01 \x01(\x07\x12\x0b\n\x03odr\x18\x02 \x01(\r\x12\x0f\n\x07\x61\x63\x63_fsr\x18\x03 \x01(\r\x12\x10\n\x08gyro_fsr\x18\x04 \x01(\r\x12)\n\tdata_sink\x18\x05 \x01(\x0e\x32\x16.bluetera.DataSinkType\"L\n\nImuCommand\x12#\n\x05start\x18\x01 \x01(\x0b\x32\x12.bluetera.ImuStartH\x00\x12\x0e\n\x04stop\x18\x02 \x01(\x08H\x00\x42\t\n\x07payload\"f\n\rUplinkMessage\x12#\n\x03imu\x18\x01 \x01(\x0b\x32\x14.bluetera.ImuCommandH\x00\x12%\n\x04\x65\x63ho\x18\x11 \x01(\x0b\x32\x15.bluetera.EchoPayloadH\x00\x42\t\n\x07payload*6\n\x13\x42lueteraModulesType\x12\n\n\x06SYSTEM\x10\x00\x12\x07\n\x03IMU\x10\x01\x12\n\n\x06SDCARD\x10\x02*A\n\x0c\x44\x61taSinkType\x12\x16\n\x12\x44\x41TA_SINK_TYPE_BLE\x10\x00\x12\x19\n\x15\x44\x41TA_SINK_TYPE_SDCARD\x10\x01*F\n\x0bImuDataType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nQUATERNION\x10\x01\x12\x11\n\rACCELEROMETER\x10\x02\x12\x07\n\x03RAW\x10\x04\x62\x06proto3')
)

_BLUETERAMODULESTYPE = _descriptor.EnumDescriptor(
  name='BlueteraModulesType',
  full_name='bluetera.BlueteraModulesType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYSTEM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMU', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SDCARD', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=823,
  serialized_end=877,
)
_sym_db.RegisterEnumDescriptor(_BLUETERAMODULESTYPE)

BlueteraModulesType = enum_type_wrapper.EnumTypeWrapper(_BLUETERAMODULESTYPE)
_DATASINKTYPE = _descriptor.EnumDescriptor(
  name='DataSinkType',
  full_name='bluetera.DataSinkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_SINK_TYPE_BLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_SINK_TYPE_SDCARD', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=879,
  serialized_end=944,
)
_sym_db.RegisterEnumDescriptor(_DATASINKTYPE)

DataSinkType = enum_type_wrapper.EnumTypeWrapper(_DATASINKTYPE)
_IMUDATATYPE = _descriptor.EnumDescriptor(
  name='ImuDataType',
  full_name='bluetera.ImuDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUATERNION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCELEROMETER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=946,
  serialized_end=1016,
)
_sym_db.RegisterEnumDescriptor(_IMUDATATYPE)

ImuDataType = enum_type_wrapper.EnumTypeWrapper(_IMUDATATYPE)
SYSTEM = 0
IMU = 1
SDCARD = 2
DATA_SINK_TYPE_BLE = 0
DATA_SINK_TYPE_SDCARD = 1
UNKNOWN = 0
QUATERNION = 1
ACCELEROMETER = 2
RAW = 4



_ECHOPAYLOAD = _descriptor.Descriptor(
  name='EchoPayload',
  full_name='bluetera.EchoPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='bluetera.EchoPayload.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=65,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='bluetera.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='bluetera.Error.module', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='bluetera.Error.code', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=135,
)


_IMUACCELERATIONPAYLOAD = _descriptor.Descriptor(
  name='ImuAccelerationPayload',
  full_name='bluetera.ImuAccelerationPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bluetera.ImuAccelerationPayload.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='bluetera.ImuAccelerationPayload.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='bluetera.ImuAccelerationPayload.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='bluetera.ImuAccelerationPayload.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=213,
)


_IMUQUATERNIONPAYLOAD = _descriptor.Descriptor(
  name='ImuQuaternionPayload',
  full_name='bluetera.ImuQuaternionPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bluetera.ImuQuaternionPayload.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='bluetera.ImuQuaternionPayload.w', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='bluetera.ImuQuaternionPayload.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='bluetera.ImuQuaternionPayload.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='bluetera.ImuQuaternionPayload.z', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=300,
)


_DOWNLINKMESSAGE = _descriptor.Descriptor(
  name='DownlinkMessage',
  full_name='bluetera.DownlinkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='bluetera.DownlinkMessage.acceleration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quaternion', full_name='bluetera.DownlinkMessage.quaternion', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='bluetera.DownlinkMessage.error', index=2,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='echo', full_name='bluetera.DownlinkMessage.echo', index=3,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='bluetera.DownlinkMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=303,
  serialized_end=516,
)


_IMUSTART = _descriptor.Descriptor(
  name='ImuStart',
  full_name='bluetera.ImuStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_types', full_name='bluetera.ImuStart.data_types', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='odr', full_name='bluetera.ImuStart.odr', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_fsr', full_name='bluetera.ImuStart.acc_fsr', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_fsr', full_name='bluetera.ImuStart.gyro_fsr', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_sink', full_name='bluetera.ImuStart.data_sink', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=639,
)


_IMUCOMMAND = _descriptor.Descriptor(
  name='ImuCommand',
  full_name='bluetera.ImuCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='bluetera.ImuCommand.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='bluetera.ImuCommand.stop', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='bluetera.ImuCommand.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=641,
  serialized_end=717,
)


_UPLINKMESSAGE = _descriptor.Descriptor(
  name='UplinkMessage',
  full_name='bluetera.UplinkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imu', full_name='bluetera.UplinkMessage.imu', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='echo', full_name='bluetera.UplinkMessage.echo', index=1,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='bluetera.UplinkMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=719,
  serialized_end=821,
)

_ERROR.fields_by_name['module'].enum_type = _BLUETERAMODULESTYPE
_DOWNLINKMESSAGE.fields_by_name['acceleration'].message_type = _IMUACCELERATIONPAYLOAD
_DOWNLINKMESSAGE.fields_by_name['quaternion'].message_type = _IMUQUATERNIONPAYLOAD
_DOWNLINKMESSAGE.fields_by_name['error'].message_type = _ERROR
_DOWNLINKMESSAGE.fields_by_name['echo'].message_type = _ECHOPAYLOAD
_DOWNLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _DOWNLINKMESSAGE.fields_by_name['acceleration'])
_DOWNLINKMESSAGE.fields_by_name['acceleration'].containing_oneof = _DOWNLINKMESSAGE.oneofs_by_name['payload']
_DOWNLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _DOWNLINKMESSAGE.fields_by_name['quaternion'])
_DOWNLINKMESSAGE.fields_by_name['quaternion'].containing_oneof = _DOWNLINKMESSAGE.oneofs_by_name['payload']
_DOWNLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _DOWNLINKMESSAGE.fields_by_name['error'])
_DOWNLINKMESSAGE.fields_by_name['error'].containing_oneof = _DOWNLINKMESSAGE.oneofs_by_name['payload']
_DOWNLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _DOWNLINKMESSAGE.fields_by_name['echo'])
_DOWNLINKMESSAGE.fields_by_name['echo'].containing_oneof = _DOWNLINKMESSAGE.oneofs_by_name['payload']
_IMUSTART.fields_by_name['data_sink'].enum_type = _DATASINKTYPE
_IMUCOMMAND.fields_by_name['start'].message_type = _IMUSTART
_IMUCOMMAND.oneofs_by_name['payload'].fields.append(
  _IMUCOMMAND.fields_by_name['start'])
_IMUCOMMAND.fields_by_name['start'].containing_oneof = _IMUCOMMAND.oneofs_by_name['payload']
_IMUCOMMAND.oneofs_by_name['payload'].fields.append(
  _IMUCOMMAND.fields_by_name['stop'])
_IMUCOMMAND.fields_by_name['stop'].containing_oneof = _IMUCOMMAND.oneofs_by_name['payload']
_UPLINKMESSAGE.fields_by_name['imu'].message_type = _IMUCOMMAND
_UPLINKMESSAGE.fields_by_name['echo'].message_type = _ECHOPAYLOAD
_UPLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _UPLINKMESSAGE.fields_by_name['imu'])
_UPLINKMESSAGE.fields_by_name['imu'].containing_oneof = _UPLINKMESSAGE.oneofs_by_name['payload']
_UPLINKMESSAGE.oneofs_by_name['payload'].fields.append(
  _UPLINKMESSAGE.fields_by_name['echo'])
_UPLINKMESSAGE.fields_by_name['echo'].containing_oneof = _UPLINKMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['EchoPayload'] = _ECHOPAYLOAD
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ImuAccelerationPayload'] = _IMUACCELERATIONPAYLOAD
DESCRIPTOR.message_types_by_name['ImuQuaternionPayload'] = _IMUQUATERNIONPAYLOAD
DESCRIPTOR.message_types_by_name['DownlinkMessage'] = _DOWNLINKMESSAGE
DESCRIPTOR.message_types_by_name['ImuStart'] = _IMUSTART
DESCRIPTOR.message_types_by_name['ImuCommand'] = _IMUCOMMAND
DESCRIPTOR.message_types_by_name['UplinkMessage'] = _UPLINKMESSAGE
DESCRIPTOR.enum_types_by_name['BlueteraModulesType'] = _BLUETERAMODULESTYPE
DESCRIPTOR.enum_types_by_name['DataSinkType'] = _DATASINKTYPE
DESCRIPTOR.enum_types_by_name['ImuDataType'] = _IMUDATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoPayload = _reflection.GeneratedProtocolMessageType('EchoPayload', (_message.Message,), dict(
  DESCRIPTOR = _ECHOPAYLOAD,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.EchoPayload)
  ))
_sym_db.RegisterMessage(EchoPayload)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.Error)
  ))
_sym_db.RegisterMessage(Error)

ImuAccelerationPayload = _reflection.GeneratedProtocolMessageType('ImuAccelerationPayload', (_message.Message,), dict(
  DESCRIPTOR = _IMUACCELERATIONPAYLOAD,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.ImuAccelerationPayload)
  ))
_sym_db.RegisterMessage(ImuAccelerationPayload)

ImuQuaternionPayload = _reflection.GeneratedProtocolMessageType('ImuQuaternionPayload', (_message.Message,), dict(
  DESCRIPTOR = _IMUQUATERNIONPAYLOAD,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.ImuQuaternionPayload)
  ))
_sym_db.RegisterMessage(ImuQuaternionPayload)

DownlinkMessage = _reflection.GeneratedProtocolMessageType('DownlinkMessage', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLINKMESSAGE,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.DownlinkMessage)
  ))
_sym_db.RegisterMessage(DownlinkMessage)

ImuStart = _reflection.GeneratedProtocolMessageType('ImuStart', (_message.Message,), dict(
  DESCRIPTOR = _IMUSTART,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.ImuStart)
  ))
_sym_db.RegisterMessage(ImuStart)

ImuCommand = _reflection.GeneratedProtocolMessageType('ImuCommand', (_message.Message,), dict(
  DESCRIPTOR = _IMUCOMMAND,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.ImuCommand)
  ))
_sym_db.RegisterMessage(ImuCommand)

UplinkMessage = _reflection.GeneratedProtocolMessageType('UplinkMessage', (_message.Message,), dict(
  DESCRIPTOR = _UPLINKMESSAGE,
  __module__ = 'bluetera_messages_pb2'
  # @@protoc_insertion_point(class_scope:bluetera.UplinkMessage)
  ))
_sym_db.RegisterMessage(UplinkMessage)


# @@protoc_insertion_point(module_scope)
